### PR TITLE
#34: simplify local environment installation

### PR DESCRIPTION
**Pull request by eliskovets**
This configuration should simplify local environment and make an easy start for every new developer in the project.
Automatic docker image publishing for tags has been also configured. We just need to prepare DOCKER_USERNAME and DOCKER_PASSWORD environment variables on Travis side.

### CODE REVIEW

**Comment by ceckoslab** [comment]
Hello @eliskovets ,

First I run `make up` but when I run `make init` I get an error:

```
cat init.sh >init 
/bin/sh: 1: cannot create init: Permission denied
<builtin>: recipe for target 'init' failed
make: *** [init] Error 2
```

Could this be because because I am running linux?

Full command log:

```
tsvetan@tsvetan-XPS-15-9550:~/projects/basicrum/backoffice$ make init
docker-compose -f docker/docker-compose.yml up -d --build
Building crons
Step 1/7 : ARG PHP_VERSION="7.3"
Step 2/7 : FROM php:${PHP_VERSION}-cli-alpine
 ---> 2f43b02d182f
Step 3/7 : RUN apk add --no-cache zip bash libzip     && apk add --no-cache --virtual .build-deps libzip-dev     && docker-php-ext-configure zip --with-libzip     && docker-php-ext-install pdo_mysql zip      && apk del --purge .build-deps
 ---> Using cache
 ---> 3de22344de4c
Step 4/7 : COPY crontab /etc/crontabs/basicrum
 ---> Using cache
 ---> cc21bd17a8ff
Step 5/7 : RUN crontab -u www-data /etc/crontabs/basicrum
 ---> Using cache
 ---> 6385643e703b
Step 6/7 : ENTRYPOINT []
 ---> Running in 0e6fc7bf182e
Removing intermediate container 0e6fc7bf182e
 ---> f9ad8f6b45d4
Step 7/7 : CMD ["crond", "-f", "-L", "/dev/stderr"]
 ---> Running in ab2be61a38bc
Removing intermediate container ab2be61a38bc
 ---> 5397b81c0318

Successfully built 5397b81c0318
Successfully tagged docker_crons:latest
Building symfony_app
Step 1/4 : ARG PHP_VERSION="7.3"
Step 2/4 : FROM php:${PHP_VERSION}-fpm-alpine
 ---> b817a793087a
Step 3/4 : RUN apk add --no-cache zip bash libzip     && apk add --no-cache --virtual .build-deps libzip-dev     && docker-php-ext-configure zip --with-libzip     && docker-php-ext-install pdo_mysql zip      && apk del --purge .build-deps
 ---> Using cache
 ---> 1293bf6b421d
Step 4/4 : RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"     && php composer-setup.php --filename=composer --install-dir=/usr/local/bin     && php -r "unlink('composer-setup.php');"
 ---> Using cache
 ---> bffb974552e1

Successfully built bffb974552e1
Successfully tagged docker_symfony_app:latest
basicrum_bo_mysql is up-to-date
basicrum_bo_php is up-to-date
Recreating basicrum_bo_crons ... 
basicrum_bo_phpmyadmin is up-to-date
Recreating basicrum_bo_crons ... done
docker-compose -f docker/docker-compose.yml exec symfony_app ./chown.sh
docker-compose -f docker/docker-compose.yml exec -T --user=www-data symfony_app ./init.sh
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [OK]
Executing script assets:install public [OK]

Migration completed!
docker-compose -f docker/docker-compose.yml exec --user=www-data symfony_app ./bin/console basicrum:superadmin:create
Please enter Super User first name : Tsvetan    
Please enter Super User last name : Stoychev
Please enter Super User email : ceckoslab@gmail.com	
Please enter Super User password : 
Super User password again : 

                                                                                                                        
 [OK] Super admin user with email ceckoslab@gmail.com has been created!                                                 
       You may now login using registred email and password!                                                            
                                                                                                                        

docker-compose -f docker/docker-compose.yml exec -T --user=www-data symfony_app ./bin/console cache:clear

 // Clearing the cache for the dev environment with debug                       
 // true                                                                        

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    

docker-compose -f docker/docker-compose.yml exec -T --user=www-data symfony_app ./bin/console basicrum:cache:clean
docker-compose -f docker/docker-compose.yml exec -T --user=www-data symfony_app ./bin/console basicrum:beacon:init-folders
Directory already exist: /var/www/html/var/beacons
Directory already exist: /var/www/html/var/beacons/raw
Directory already exist: /var/www/html/var/beacons/archive
Directory already exist: /var/www/html/var/beacons/bundles
cat init.sh >init 
/bin/sh: 1: cannot create init: Permission denied
<builtin>: recipe for target 'init' failed
make: *** [init] Error 2
```

**Comment by ceckoslab** [comment]
Hello @eliskovets 

I faced another issue where files' group and owner were changed on the host machine. I think that this is something specific for Linux.

The problem now is that now I can't modify any files in backoffice project:

Screenshot from 2020-05-02 15-48-39

This is how things look on the files system:
```
drwxr-xr-x  2      82      82 4,0K Mär 26 16:52 assets
drwxr-xr-x  3      82      82 4,0K Jun  6  2019 bin
-rwxr-xr-x  1      82      82   99 Mai  2 15:17 chown.sh
-rw-r--r--  1      82      82 2,4K Apr  3 22:27 composer.json
...
```

I see 82:82 where I would expect to have tsvetan:tsvetan 

I guess that this is a side effect of the chown command and how Docker works under Linux.

**Comment by ceckoslab** [comment]
Hello @eliskovets 

For local development could we add `APP_ENV = dev` because right now I am getting an error message for all diagrams.

The problem appears here and I know that this is not the perfect implementation:

**src/BasicRum/Cache/Storage.php**
```
public function __construct(string $namespace = '', int $defaultLifetime = 0)
{
    $projectDir = explode('/src/BasicRum', __DIR__)[0];
    $cacheDir = $projectDir.'/var/cache/'.$_ENV['APP_ENV'];

    parent::__construct($namespace, $defaultLifetime, $cacheDir);
}
```

**Comment by ceckoslab** [comment]
Hello @eliskovets 

Could we also skip the ".git" folder while doing shown for dev environment? 

I think this will protect us from unexpected problems when people run our setup on different Operating Systems.

Thanks.

**Comment by eliskovets** [comment]
Hi @ceckoslab 
Thank you for reporting these issues. 
I've prepared a fix for linux system. Hope it will work for you as well. 
Please let me know if it doesn't. 

Travis CI is failing because of some deprecation: 
```
  20x: Using the WebserverBundle is deprecated since Symfony 4.4. The new Symfony local server has more features, you can use it instead.
    4x in ChunkTest::setUp from App\Tests\BasicRum\Visit\Calculator\Aggregator
    2x in DeviceTypeTest::setUp from App\Tests\BasicRum\Layers\DataLayer\Query
    2x in FirstByteFilterTest::setUp from App\Tests\BasicRum\Layers\DataLayer\Query
    2x in FirstPaintFilterTest::setUp from App\Tests\BasicRum\Layers\DataLayer\Query
    2x in QueryParamLikeTest::setUp from App\Tests\BasicRum\Layers\DataLayer\Query
    2x in VisitGenerateTestCase::setUp from App\Tests\BasicRum\Task
    1x in SimpleImportTest::setUp from App\Tests\BasicRum\Beacon
    1x in UserAgentImportTest::setUp from App\Tests\BasicRum\Beacon
    1x in FirstPaintSelectTest::setUp from App\Tests\BasicRum\Layers\DataLayer\Query
    1x in MinMaxPageViewIdNotFound::setUp from App\Tests\BasicRum\Layers\DataLayer\Query
    1x in UrlLikeTest::setUp from App\Tests\BasicRum\Layers\DataLayer\Query
    1x in CreateSuperadmintUserCommandTest::testExecute from App\Command
```

**Comment by ceckoslab** [comment]
Hello @eliskovets 

That's really interesting because we upgraded to Symfony 5.x 

I don't think that any of us is using this bundle. Feel free to remove it as part of this MR:

```
composer remove symfony/web-server-bundle
```

**Comment by ceckoslab** [comment]
LGTM!

**Pull request merged**
