### PR TITLE
Users CRUD, login, registration, reset password and edit profile functionality

### PR DESCRIPTION
**Pull request by korzol**
Comments are welcome

### CODE REVIEW

**Comment by ceckoslab** [comment]
Hello @korzol 

Thanks for the great work so far.

Could we add the following things as well:
1. Remove the logic related to "doctrine/doctrine-fixtures-bundle" but use Symfony Command to create an Admin User. If an admin user exists then the Symfony Command should not create a new master admin but prompt a message that a Master Admin already exists.
2. Document how admin is created, how admin user can create other users from admin interface.
3. For migration scripts add the changes needed only for user table. I see more changes in the migration and I believe that they exists because of the test DB that was provided but let's figure out why this happens later in another task.
4. We should use **var** instead of **let** in our JS files. So far I would like to keep our JS ES5 compatible.

**Comment by korzol** [comment]
>Document how admin is created, how admin user can create other users from admin interface.

What format do you prefer? Word, plain text etc.. Should I push a file into repo or use existing README.md?

**Comment by korzol** [comment]
> Do not hardcode email addresses.  

There are two possible ways to let somebody set system emails:  
1. Config files  
2. A settings page in admin area  

Which one do you prefer ?

**Comment by ceckoslab** [comment]
Hello @korzol 

1. Documentation:
Use the README file. Add a new section and use markdown in order to format the added text.

2. A settings page in admin area: 
Use a setting in the DB. Probably later we will have a page from where we will change different system variables like this email ....

**Pull request merged**
