### PR TITLE
Issue/#48 document the full installation process

### PR DESCRIPTION
**Pull request by korzol**
Hello @ceckoslab 
Here is latest changes to installation documentation (README.txt) and better creation handling.
Also I left only one but complete migration file

### CODE REVIEW

**Comment by ceckoslab** [comment]
Hello @korzol 

I see that some files were removed from folder  tests/BasicRum/Visit/Claculator

I am not sure that we need to do this? Is there a special reason who the files were removed?

**Comment by korzol** [comment]
Good question because I did not remove them. And more so they are still in filesystem but out of git control. I noticed that and wanted to ask you if they are not kind of autogenerated and if I should add them to repo

**Comment by korzol** [comment]
Got it. Going to fix it

**Comment by korzol** [comment]
@ceckoslab  Kindly review it now

**Comment by ceckoslab** [comment]
LGTM!

**Pull request merged**
